name: CI + Deploy Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - run: npm install

      - run: npm test -- --watch=false

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - run: npm install

      - run: npm run lint

  build:
    needs:
      - test
      - lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - run: npm install

      - name: Build development
        run: |
          npm run build -- \
            --configuration development \
            --base-href /angular-single-deploy/dev/ \
            --output-path dist/dev

      - name: Log File System
        run: |
          echo "File System"
          cd dist
          ls -la

      - name: Build production
        run: |
          npm run build -- \
            --configuration production \
            --base-href /angular-single-deploy/prod/ \
            --output-path dist/prod

      - name: Prepare Pages artifact
        run: |
          mkdir -p pages/dev
          mkdir -p pages/prod

          cp -r dist/dev/browser/* pages/dev
          cp -r dist/prod/browser/* pages/prod
      - name: Inspect Pages artifact
        run: |
          find pages -maxdepth 2 -type f

      - name: Log File System
        run: |
          echo "File System"
          cd dist 
          ls -la

      - uses: actions/upload-pages-artifact@v3
        with:
          path: pages
          name: upload_my_artifact

  deploy:
    needs: build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
